### ISSUE TITLE
Integers instead of floating point numbers in value_text_box

### ISSUE THREAD

**Issue by taurgal** [cedlemo/blingbling#31]
In  value_text_box.lua I changed
`local value = (data[vt_box].value or 0) * 100`
to 
`local value = math.ceil(data[vt_box].value or 0) * 100)`
to have nice integers (number of new messages in mailbox or battery remaining...)
Probably would be better if we could toggle this with a parameter...

**Comment by cedlemo** [comment]
Sorry for the late response, I will work on it today.

**Comment by cedlemo** [comment]
I have done some modifications. As for the other graphical widgets, I have added the property "value_format" which is by default "%2.f".

here is the ldoc:
```lua
---Define displayed text value format string
--@usage mypgraph:set_value_format(string) --> "%2.f"
--@name set_value_format
--@class function
--@param printf format string for display text
```

And the related code:

```lua
  local value = string.format(props.value_format,
                              data[vt_box].value * 100)
```
Note that the default value format (defined in superproperties.lua is "%2.f"

So this allow you to configure how the value should be displayed. For example : 
*    value = 5.33,  label = "a value: %percent" will display "a value :  5"
*    value = 10.60 label = "a value: %percent" will display "a value :11"

If you want to display the decimal part, you can use for example a "value_format" property equal to
"%2.2.f"

See here for more informations:

http://lua-users.org/wiki/StringLibraryTutorial

FYI:
I will made a lot of modifications on value_text_box.lua:

*     clean the code (simplify and refactoring)
*     use Pango layout instead of cr:text

Could you, please, show me some examples of your usage of value_text_box.lua.
