### ISSUE TITLE
How to run a custom function when clicking a widget? (net widget)

### ISSUE THREAD

**Issue by ViktorNova** [cedlemo/blingbling#35]
I apologize if this is a stupid question - I've done lots of fine customization of Awesome, just can't seem to figure this one out.

I want to run nmcli_dmenu when clicking the net widget, and every attempt I've made at accomplish this is resulting in errors =) I'm assuming this is simple to do?

**Comment by cedlemo** [comment]
This is not that complicated:

In order to launch a command you should use : `awul.util.spawn` see http://awesome.naquadah.org/doc/api/modules/awful.util.html#spawn .
This command is used in your rc.lua in order to launch terminal.

It seems that here you want to launch a command line tool so you have to launch your prefered terminal with the execute option `xterm [-options ...] [-e command args]` for example.

The command should be : 

    awful.util.spawn('xterm -e htop')

After that you just have to bind this command to the click signal.

**Comment by ViktorNova** [comment]
Thank you for helping - I should have been more clear, the specific issue I'm having is I don't know how to actually connect a click signal *to* the blingbling net widget

I assume I'm probably missing a fundamental understanding about how Awesome works, it hasn't all clicked for me yet but I'm getting there =) thanks again!

**Comment by cedlemo** [comment]
Ha ok, 

look at this (it is in the volume.lua file)

```lua
local function set_alsa_control(volume_graph)
   volume_graph:buttons(awful.util.table.join(
	   awful.button({ }, 1, function()
		 set_alsa_master(data[volume_graph].cmd, "toggle")
	   end),
	   awful.button({ }, 5, function()
		 set_alsa_master(data[volume_graph].cmd, data[volume_graph].increment .. "%-")
	   end),
	   awful.button({ }, 4, function()
		 set_alsa_master(data[volume_graph].cmd, data[volume_graph].increment .. "%+")
   end)))
end

```

now the api explained:
*    http://awesome.naquadah.org/doc/api/modules/wibox.widget.base.html
each Awesome widget (fro your information, all awesome widget are based on the widget.base even the blingbling widgets) have a `buttons()` method in order to define the widget buttons

*    http://awesome.naquadah.org/doc/api/modules/awful.util.html#util.table.join
This is used to create one table with the tables you put in arguments

*    http://awesome.naquadah.org/doc/api/modules/awful.button.html

this is how you create a button ( == link a mouse event to a widget)

for example:

```lua
   volume_graph:buttons(awful.util.table.join(
        awful.button({ }, 1, function()
	      awful.util.spawn_with_shell("pactl set-sink-mute @DEFAULT_SINK@ toggle")
	end),
```

this make the volume_graph widget react to the left click (the "1") and launch the `awful.util.spawn`

In your rc.lua you should try something like that:

```lua
mynet = blingbling.net({})
mynet:buttons (
 --your code here
)
```

Now you have all the informations in order to do your own.

Try to do something and post what you have done if it doesn't work, I will help you.

**Comment by ViktorNova** [comment]
Wow, thank you so much for explaining that so well, I finally understand a big piece something about how Awesome works that had previously eluded me. 

It works perfectly! Here's what I am using 
````
    netwidget:buttons(awful.util.table.join(
        awful.button({ }, 1, function()
            awful.util.spawn("nmcli_dmenu")
    end)))
````

thanks again

**Comment by cedlemo** [comment]
You are welcome! Have fun.
